In [134]:
from collections import deque
n, m = map(int,input().split())
t = [list(input().split()) for _ in range(m)]

2 2
1 -1
-1 1

In [135]:
dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]
queue = deque()
for i in range(m):
  for j in range(n):
    if t[i][j] == '1':
      queue.append([i, j])
def dfs(m, n, te, queue):
  c = [[0]*n for _ in range(m)]
  z = 0
  for i in range(m):
    for j in range(n):
      if t[i][j] == '0':
        z += 1
  if z == 0:
    return(0)
  while queue:
    a, b = queue.popleft()
    for k in range(4):
      x = a + dx[k]
      y = b + dy[k]
      if 0 <= x < m and 0 <= y < n and t[x][y] == '0' and c[x][y] == 0:
        queue.append([x,y])
        t[x][y] = '1'
        c[x][y] = c[a][b] + 1
        s1, s2 = x, y
  for i in range(m):
    for j in range(n):
      if t[i][j] == '0':
        return(-1)
  return(c[s1][s2])
print(dfs(m, n, t, queue))

0